application: analog-context-835
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /javascript
  static_dir: javascript
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: gender.app



libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
